# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rTAwNLzpPsLcR646__fR2n8YcRGxCHgn
"""

#importing libraries
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris_data = load_iris()
iris = pd.DataFrame(iris_data.data)

print("features",iris_data.feature_names)
iris.head()

x=iris.values[:,0:4]
y=iris_data.target
print(x)
print(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.25,random_state=5)

c = DecisionTreeClassifier(random_state=5)

c.fit(x_train,y_train)

#prediction
x=[[6.4,1.7,6.6,2.1]]
y_pred= c.predict(x)
print(y_pred)

y_pred= c.predict(x_test)
print(y_pred)

from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
cm

"""# Plot Decision Tree"""

from sklearn import tree
tree.plot_tree(c)

text_representation=tree.export_text(c)
print(text_representation)

import matplotlib.pyplot as plt
plt.savefig('tree.png',format='png',bbox_inches='tight')

tree.export_graphviz(c)